[build]
  base = "client"
  command = "npm ci && node node_modules/react-scripts/scripts/build.js"
  publish = "build"

[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
